name: splito_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  build_runner: ^2.4.0
  riverpod_generator: ^2.3.0
  riverpod_lint: ^2.3.0
  custom_lint: ^0.5.0
  flutter_riverpod: ^2.0.0
  riverpod_annotation: ^2.0.0
  mocktail: ^1.0.4
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  shared_preferences: ^2.3.0
  fl_chart: ^0.60.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/splito.png